### ISSUE TITLE
疑似无法登录，提示get key error

### ISSUE THREAD

**Issue by tonylee-61** [valkjsaaa/auto-bilibili-recorder#11]
运行无GPU镜像，docker logs如下：

Traceback (most recent call last):
  File "/webhook/process_video.py", line 7, in <module>
    record_upload_manager = RecordUploadManager("./recorder_config.yaml", "recorder_save.yaml")
  File "/webhook/record_upload_manager.py", line 32, in __init__
    self.config = RecorderConfig(yaml.load(file, Loader=yaml.FullLoader))
  File "/webhook/recorder_config.py", line 52, in __init__
    self.accounts = {name: UploaderAccount(account) for name, account in config_dict['accounts'].items()}
  File "/webhook/recorder_config.py", line 52, in <dictcomp>
    self.accounts = {name: UploaderAccount(account) for name, account in config_dict['accounts'].items()}
  File "/webhook/recorder_config.py", line 21, in __init__
    self.login()
  File "/webhook/recorder_config.py", line 27, in login
    b.login(username=self.username, password=self.password)
  File "/webhook/bilibili.py", line 315, in login
    elif self.username and self.password and by_password():
  File "/webhook/bilibili.py", line 250, in by_password
    key = get_key()
  File "/webhook/bilibili.py", line 247, in get_key
    raise Exception("Login: get key error!")
Exception: Login: get key error!

已确认过账号密码正确，手机号及邮箱作为username均无法登录

**Comment by Johnnylov** [comment]
可以询问邮箱，解决了嘛

**Comment by valkjsaaa** [comment]
加入了用 sessdata 和 bili_jct 登陆，试试看
