### ISSUE TITLE
生成弹幕高能列表时报错

### ISSUE THREAD

**Issue by JIBING0913** [valkjsaaa/auto-bilibili-recorder#17]
/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py:24: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import convolve
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.321 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 503, in <module>
    wordcount_slices = gen_slice_wordcount(slices)
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 91, in gen_slice_wordcount
    return [Counter(jieba.cut(" ".join(slice))) for slice in danmaku_slices]
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 91, in <listcomp>
    return [Counter(jieba.cut(" ".join(slice))) for slice in danmaku_slices]
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by valkjsaaa** [comment]
弹幕 xml 发一下？看起来像是完全没有弹幕？会不会？

**Comment by JIBING0913** [comment]
[danmu.xml.zip](https://github.com/valkjsaaa/auto-bilibili-recorder/files/8260320/danmu.xml.zip)
这个是出错的弹幕文件，弹幕分析脚本只自动生成了SC列表。
我用之前版本的弹幕分析脚本可以正常解析，新版的就会报错。。。

**Comment by Shiori514** [comment]
貌似是 danmaku_tools 更新了这一部分导致的，临时修复可以先进容器
`docker exec -it auto-bilibili-recorder bash`
回退到更新前的版本
`pip3 install git+https://github.com/valkjsaaa/danmaku_tools.git@a3cfbf7c8fa0905d9fbb4d49f8d824d3f48b426e`
退出重启容器
`exit`
`docker restart auto-bilibili-recorder`
