### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by ZoidbergPi** [valkjsaaa/auto-bilibili-recorder#29]
`{'event': 'PRE_UPLOAD_PROBE', 'ok': True, 'data': {'OK': 1, 'lines': [{'os': 'upos', 'query': 'probe_version=20211012&upcdn=qn&zone=cs', 'probe_url': '//upos-cs-upcdnqn.bilivideo.com/OK'}, {'os': 'upos', 'query': 'probe_version=20211012&upcdn=bda2&zone=cs', 'probe_url': '//upos-cs-upcdnbda2.bilivideo.com/OK'}], 'probe': {'post': 0.1}}}
{'event': 'PRE_UPLOAD', 'ok': False, 'data': JSONDecodeError('Expecting value: line 1 column 1 (char 0)')}
Upload failed too many times: 
Traceback (most recent call last):
  File "/webhook/record_upload_manager.py", line 68, in video_uploader
    bv_id = upload_task.upload(self.save.session_id_map)
  File "/webhook/upload_task.py", line 34, in upload
    filename = video_upload(self.video_path, verify=self.verify, on_progress=on_progress)
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/video.py", line 1250, in video_upload
    raise e
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/video.py", line 1237, in video_upload
    settings = resp.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

多次重试后失败，之前录播上传都是成功的，没有看到请求，使用docker-gpu:master来启动的

**Comment by valkjsaaa** [comment]
修好啦。 pull 最新的 master 再试试 🥳
