### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by ZoidbergPi** [valkjsaaa/auto-bilibili-recorder#36]
docker logs日志：
线路选择 => cos: . time: None
os: cos
Upload failed too many times:  
Traceback (most recent call last):
  File "/webhook/record_upload_manager.py", line 68, in video_uploader
    bv_id = upload_task.upload(self.save.session_id_map)
  File "/webhook/upload_task.py", line 34, in upload
    filename = video_upload(self.video_path, verify=self.verify, on_progress=on_progress, server='cos')
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/video.py", line 1484, in video_upload
    return asyncio.run(upload(f, total_size, ret.json(), tasks=tasks))['filename']
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

重新登录之后可以上传，这种是不是token过期的问题？

**Comment by valkjsaaa** [comment]
对
