### ISSUE TITLE
一直在反复重启

### ISSUE THREAD

**Issue by MrZhongzq** [valkjsaaa/auto-bilibili-recorder#40]
镜像启动以后报了一个显卡驱动错误，然后提示login successfully，接着就是python报错，启动30秒不到就开始反复容器重启，我连日志都截取不了。但是我拉取的是无gpu的镜像啊

**Comment by MrZhongzq** [comment]
我不太清楚是不是我的yaml的问题，但是我直接复制github事例改的，应该没问题

**Comment by MrZhongzq** [comment]
我调整recoder_config以后已经可以启动不崩溃,但是日志里有如下错误
[2022-10-02 20:10:19,280] ERROR in app: Exception on request POST /process_video
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1629, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1654, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1099, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1652, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1697, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/webhook/process_video.py", line 14, in respond_process
    await record_upload_manager.handle_update(json_request)
  File "/webhook/record_upload_manager.py", line 244, in handle_update
    session_id = update_json["EventData"]["SessionId"]
KeyError: 'SessionId'
[20:10:19 WRN (BililiveRecorder.Core.SimpleWebhook.BasicWebhookV2)] 发送 WebhookV2 到 http://127.0.0.1:10261/process_video 失败
    [System.Net.Http.HttpRequestException]: Response status code does not indicate success: 500 ().
[2022-10-02 20:10:19 +0800] [9] [INFO] 127.0.0.1:47154 POST /process_video 1.1 500 265 7936
