### ISSUE TITLE
录制过程中出错

### ISSUE THREAD

**Issue by MrZhongzq** [valkjsaaa/auto-bilibili-recorder#41]
[2022-10-02 21:07:30,973] ERROR in app: Exception on request POST /process_video
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1629, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1654, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1099, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1652, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 1697, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/webhook/process_video.py", line 14, in respond_process
    await record_upload_manager.handle_update(json_request)
  File "/webhook/record_upload_manager.py", line 244, in handle_update
    session_id = update_json["EventData"]["SessionId"]
KeyError: 'SessionId'
[21:07:30 WRN (BililiveRecorder.Core.SimpleWebhook.BasicWebhookV2)] 发送 WebhookV2 到 http://127.0.0.1:10261/process_video 失败
    [System.Net.Http.HttpRequestException]: Response status code does not indicate success: 500 ().

似乎是无法连接webhook

**Comment by valkjsaaa** [comment]
我有点懒，新的录播姬会发一个不带 session ID 的 message，现在 python handle 不了，所以会有这个错，但是那个 message 根本不重要，所以 handle 不了也没关系。
所以你报错了之后录不了吗？

**Comment by MrZhongzq** [comment]
我现在可以正常录像，但是可能是国庆这几天b站投稿维护无法投稿？我现在是报了一个投稿功能维护请重新编辑稿件。

**Comment by valkjsaaa** [comment]
上传 API 好像有改变，这个周末我尽量改好

**Comment by valkjsaaa** [comment]
应该修了，试试看

**Comment by valkjsaaa** [comment]
我自己测试 kodo 线路很好用
