### ISSUE TITLE
录制结束后处理弹幕出现报错

### ISSUE THREAD

**Issue by ChenFu0420** [valkjsaaa/auto-bilibili-recorder#49]
在第1月9号的时候可以正常运行完整套流程，但是在第二天就无法处理录制结束后的流程了，查看了Log之后发现了报错。感觉应该是处理弹幕方面相关的，希望作者可以看看发生甚么事了
``` log
 /usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py:24: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import convolve
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.633 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 503, in <module>
    wordcount_slices = gen_slice_wordcount(slices)
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 91, in gen_slice_wordcount
    return [Counter(jieba.cut(" ".join(slice))) for slice in danmaku_slices]
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 91, in <listcomp>
    return [Counter(jieba.cut(" ".join(slice))) for slice in danmaku_slices]
TypeError: sequence item 0: expected str instance, NoneType found
```
附上弹幕文件
https://gist.github.com/ChenFu0420/4cc30452905c52961af8ba24a1f57a21

**Comment by ChenFu0420** [comment]
问题已经解决，请参考 https://github.com/valkjsaaa/danmaku_tools/issues/7#issue-1355280654
