### ISSUE TITLE
字幕超过限制

### ISSUE THREAD

**Issue by TKK4396** [valkjsaaa/auto-bilibili-recorder#51]
字幕多的时候出现了这个报错，后面一直在重试
日志如下：
Traceback (most recent call last):
  File "/webhook/subtitle_task.py", line 83, in post_subtitle
    video.save_subtitle(srt_json_str, bvid=self.bvid, cid=self.cid, verify=verify)
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/video.py", line 991, in save_subtitle
    resp = utils.post(url=api["url"], data=data, cookies=verify.get_cookies())
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/utils.py", line 430, in post
    resp = request("POST", url=url, data=data, cookies=cookies, headers=headers, data_type=data_type, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bilibili_api/utils.py", line 391, in request
    raise exceptions.BilibiliException(con["code"], msg)
bilibili_api.exceptions.BilibiliException: 错误代码：79014, 信息：字幕超过限制

**Comment by TKK4396** [comment]
sc留言和高能标记留言是生成了的

**Comment by TKK4396** [comment]
文件大小如下：
19M 1月  27 23:44 21416935-20230127-220357-227.all.ass 
477M 1月  27 23:40 21416935-20230127-220357-227.all.clean.xml

**Comment by TKK4396** [comment]
文件大小如下：
19M 20230127-220357-227.all.ass
477M 220357-227.all.clean.xml

**Comment by TKK4396** [comment]
> 字母是管 sc 的，不是你发的那个 应该是某个以 he.srt 结尾的，发上来看看？

he.srt结尾的文件好像没有生成
![Snipaste_2023-01-28_11-32-48](https://user-images.githubusercontent.com/53162862/215240024-374ed395-babd-49cc-b820-6ac54a2c3041.jpg)

**Comment by valkjsaaa** [comment]
说错了 sc.srt

**Comment by TKK4396** [comment]
> 说错了 sc.srt

[21416935-20230127-220357-227.all.sc.srt.zip](https://github.com/valkjsaaa/auto-bilibili-recorder/files/10525278/21416935-20230127-220357-227.all.sc.srt.zip)
